### ISSUE TITLE
Search broken in 7.7.2?

### ISSUE THREAD

**Issue by adminibt** [salesagility/SuiteCRM#2030]
Has somebody tested search in accounts and get a proper result? I don't.

#### Issue

Search in modules don't work as expected. A search is done but all records are beeing displayed. Only in the accounts module the search string is saved. In contacts and leads (others?) nothing is saved.

#### Expected Behavior

Search should only display the found records and the search string should be saved.

#### Actual Behavior

See above and the screenshot
![search772](https://cloud.githubusercontent.com/assets/19223035/17933529/b0991cec-6a14-11e6-81d6-1ab713f070df.png)

#### Steps to Reproduce

1. Clean install of 7.7.2
2. Create 5 accounts
3. Search in accounts module

#### Your Environment

* SuiteCRM Version used: 7.7.2
* FF 48.0.1
* PHP 5.6, Mysql 5.6
* FreeBSD 10.2

**Comment by primozn** [comment]
Same problem here.

My environment:
PHP 7.0.5, Apache 2.4.18

**Comment by mikesolo** [comment]
To fix this add $this->searchFields = $searchFields[$this->module]; on line 130

**Comment by primozn** [comment]
Which file?

**Comment by mikesolo** [comment]
include/SearchForm/SearchForm2.php

sorry missed the filename

**Comment by primozn** [comment]
Thank you!
Works like a charm!

**Comment by chandon** [comment]
:+1:

**Comment by staganyi** [comment]
I can also confirm the bug and the fix on a clean install of 7.2.2

**Comment by tfreier** [comment]
I have the same issue. It worked fine with 7.2.1 and broke after upgrading to 7.2.2.

**Comment by sieberta** [comment]
Bug real, fix real.  Also was hoping this fix would take care of favorites search not working... no such luck.

**Comment by noelhunter** [comment]
The fix corrects the problem with no results, but custom modules in basic search return all rows.

**Comment by irgreeny** [comment]
Global (in basic) search return all rows too...

**Comment by samus-aran** [comment]
This is resolved in Release 7.7.3  Let us know if this needs to be re-opened.

**Comment by noelhunter** [comment]
Custom modules for me are still returning all rows in basic search

**Comment by staganyi** [comment]
The basic & adv searches work for my custom modules on 7.7.3

**Comment by noelhunter** [comment]
Advance searches work for me, but my custom module returns all rows in basic search.  Could be my module-- someone else can verify if they also have the problem in basic search.  I switched to advanced for now.

**Comment by gnurob** [comment]
I picked this up in 7.7.2 and upgraded to 7.7.4, skipping 7.7.3, and the problem persists in basic and advanced searches for contacts/leads/targets (and possibly other places).

**Comment by gnurob** [comment]
@samus-aran how do you let someone know this needs to be re-opened?
