### ISSUE TITLE
Attaching document send E-Mail

### ISSUE THREAD

**Issue by halest** [salesagility/SuiteCRM#3788]
#### Issue
When in composer, clicking "Attach Document" immediatly sends the mail

#### Expected Behavior
Showing a document-selection-popup

#### Actual Behavior
E-Mail is sent

#### Steps to Reproduce

1. Open composer
2. Click "Attach document"
3. Popup shows "E-Mail was sent"
4.

#### Context

Makes E-mail unusable for us

#### Your Environment

* SuiteCRM Version used: 7.9.1
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)): FF 52
* Environment name and version (e.g. MySQL, PHP 7): MSSQL, PHP 7
* Operating System and version (e.g Ubuntu 16.04): Windows Server 2008R2

**Comment by Dillon-Brown** [comment]
@halest This issue should be fixed. Can you check to see if your instance has the fix included here? https://github.com/salesagility/SuiteCRM/pull/3752

**Comment by halest** [comment]
Hey @Dillon-Brown . My today downloaded file (Upgrade-7.8.x-7.9.1.zip) did not include that change.
Can confirm it worked.

**Comment by halest** [comment]
Also, the same fix is necessary for self.disregardDraft or disregarding will send the mail, too which I would say is a worst-case scenario

**Comment by halest** [comment]
Created a Pull Request for both changes

**Comment by halest** [comment]
Doing the same fix on disregardDraft does not fix it. It'll create an overlay, but confirming on it still sends the mail @Dillon-Brown

**Comment by Dillon-Brown** [comment]
@halest Confirmed as a bug. I'll raise a new issue. :+1:
