### ISSUE TITLE
Activities - Compose Email - Broken in 7.10.x

### ISSUE THREAD

**Issue by LEAP-nishit** [salesagility/SuiteCRM#5639]
#### Issue

Under the activities subpanel the Compose Email fails to launch the email pop-up. This was first noticed in the Cases module but other modules have the same issues. 

![comp](https://user-images.githubusercontent.com/9854372/38184307-1dd2086c-368a-11e8-8b6c-6d8ac7d90960.png)

Inspecting the element reveals that 
```html
<li>
 <a class="email-link" href="javascript:void(0);" onclick="$(document).openComposeViewModal(this);" data-module="" data-record-id="" data-module-name="" data-email-address="">
</a>Compose Email</li>
``` 
It appears that there are two problems:
1. The string `Compose Email` is in the wrong spot
2. The function populateComposeViewFields when passed the aCase bean does not correctly populate `data-module` and `data-recore-id` and `data-email-address` for associated contact. 

#### Expected Behavior

1. The `Compose Email` should work and not be a dummy link. 
2. The correct module and related id should be populated for the Cases Module
3. (if possible) The associated contact emails be populated in the `To:` field. 

#### Actual Behavior

Nothing happens. 
No error generated in logs. 

#### Steps to Reproduce

1. Use the demo site on suiteondemand.com
2. Go to Cases and click on a case
3. Expand the activities subpanel
4. Try to compose an email. 

#### Context

This used to work in 7.8.x. With the upgrade to 7.10 it is a disruption to existing workflow for responding to cases.

#### Your Environment

* SuiteCRM Version used: 7.10.2
* Browser: Firefox 59.0.2 and Chrome 65.0.3325.181  
* Environment: suiteondemand.com

**Comment by PedroErnst** [comment]
@LEAP-nishit 

Thanks for reporting this. I'm looking into it.

**Comment by Miroslav36** [comment]
Hello @PedroErnst ,
I confirm that this is also an issue in opportunities module.
![bug-opportunities](https://user-images.githubusercontent.com/17055131/38248050-7109804c-3747-11e8-81dd-e08ab00a94b5.png)

Your Environment
SuiteCRM Version used: 7.10.2
Browser name and version: Firefox 58, 59 and Chrome 65
Environment name and version: MariaDB 10.0.32, PHP 5.6.33
Operating System and version: Debian 8.10 (Jessie)

**Comment by pgorod** [comment]
In 7.10.4 I am seeing this in Activities subpanel, Accounts detail view:
![image](https://user-images.githubusercontent.com/15945027/38567475-3d808d3c-3cde-11e8-9afc-d5f3fef290ed.png)

**Comment by PedroErnst** [comment]
Fixed here #5640 but not merged yet

**Comment by pgorod** [comment]
I can't test right now but I suppose this also fixes #5448

**Comment by sanchezfauste** [comment]
Same issue on 7.9.17, when you click 'Compose Email' button, the email compose pop-up is not loaded properly.

A javascript error is thrown:

```javascript
Uncaught TypeError: Cannot read property 'elements' of undefined
    at n.fn.init.$.fn.openComposeViewModal (sugar_grp1_jquery.js:7660)
    at HTMLAnchorElement.onclick (index.php?action=ajaxui:1)
```

**Comment by pgorod** [comment]
The fix seems to be specific to the Opportunities module, but I'm seeing this error also in Cases module. 

Maybe this needs a more generic solution, like "if there is no email1 field in Bean, but there is a related account with an email, use that one". This would not test for the module type at all.

BTW: why is the CSS broken on the "Compose Email" button? See screenshot above.

**Comment by adeel3612** [comment]
Hey guys i know this is old issue but the css is broken and have not fixed yet?

**Comment by pgorod** [comment]
For me it's showing correctly. Are you using the latest version? Do you have any customizations to your theme?
