### ISSUE TITLE
Emails sent in 7.10.6 show as being from "Root User"

### ISSUE THREAD

**Issue by angar321** [salesagility/SuiteCRM#6012]
After upgrading to 7.10.6 if I go to Admin / Email Settings and Send Test Email it works great and when received all appears to be fine. If I then go to a contact or account and click on the email address to send an email from there everything looks fine too, but when the email is received at the other end the From name is showing as "Root User" rather than "My Company Name" which is what shows in SuiteCRM before clicking send.

Expected Behaviour
I would expect the From Name to show as "My Company Name" just as it does when test sending from the Email Settings page

Actual Behaviour
When actually sending, the email is received but shows as being from "Root User" rather than from "My Company Name" as it does when testing the settings.

Possible Fix
as suggested by another user in the forum it appears to be pulling Root User from line 79 of .../include/phpmailer/class.phpmailer.php  I suspect therefore that this needs to be edited and replaced with the correct code, but no idea what that code would be as not a developer myself

Steps to Reproduce

1. Setup email on the Admin / Email Settings Page
2. Use the button on above page to send test email, which works fine
3. Now go to a contact (whose email you have access to) and send them an email
4. Check the email that they receive and you will see it is being received from "Root User"

Context
I believe this should be a fairly simple fix, and it restricts the ability to send email from SuiteCRM until it is fixed. As such I would mark it as high priority.

Your Environment
Running SuiteCRM 7.10.6
Browser used Chrome v67
Oh and apologies if I did anything wrong here, first time posting an issue!

**Comment by angar321** [comment]
Just noticed issue #6017 which would resolve this along with other issues.

**Comment by ApatheticCosmos** [comment]
Just a heads up, my pull request doesn't fix this, and it seems to be new behavior in 7.10.6. I'll look into it. You should reopen the issue.

**Comment by ApatheticCosmos** [comment]
https://github.com/salesagility/SuiteCRM/commit/d4ad96d432ad42bbeef61240985aba5a26afab30

I think this is the commit that broke it. It's overwriting the provided to From if the mail->oe->type is 'system'.

**Comment by ApatheticCosmos** [comment]
Confirmed. https://github.com/salesagility/SuiteCRM/commit/d4ad96d432ad42bbeef61240985aba5a26afab30 is what is causing this. Following the code though the debugger, the type is set to 'system' if their is no matching *inbound* mail accounts.

**Comment by ApatheticCosmos** [comment]
Fixed in updated pull request #6017

**Comment by angar321** [comment]
fantastic thanks, will leave as closed since fixed there

**Comment by Dillon-Brown** [comment]
Hi guys, taking a look at hopefully getting this PR merged in. Would anyone be able to assist with testing? just a simple confirmation that it works for you would be greatly appreciated.

**Comment by connorshea** [comment]
Hmm, what wasn't merged here? We're still seeing this problem with 7.10.19, can it be fixed by just toggling the 'allow users to send as themselves' feature? Is there a reason we can't configure the email address that's sending the emails?

**Comment by pgorod** [comment]
@connorshea that final comment on #6017 seems to indicate the fix isn't complete yet...
