### ISSUE TITLE
Task Due Date not showing in Opporunities subpanel 

### ISSUE THREAD

**Issue by wanesmith** [salesagility/SuiteCRM#6689]
Most due dates are showing but Task Due date is still not showing. 

Could be related to #5560 but 

#### Expected Behavior

Should be able to see the due date of tasks in history subpanel
#### Actual Behavior

![image](https://user-images.githubusercontent.com/2706403/50471330-b2e52300-09e6-11e9-9a06-23859c98d89e.png)
![image](https://user-images.githubusercontent.com/2706403/50471364-d019f180-09e6-11e9-8f8c-6eb90f83635a.png)

#### Steps to Reproduce

1. Create Opportunity 
2. Create Task with due date
3. Due date does not show up in Subpanel

#### Context
Can not see Due date 

Should be medium
#### Your Environment

* SuiteCRM Version used:
Version 7.10.11

Sugar Version 6.5.25 (Build 344) (tested on demo with same results
* Browser name and version (e.g. Chrome Version 51.0.2704.63 (64-bit)):

* Environment name and version (e.g. MySQL, PHP 7):
MySQL, PHP 7
* Operating System and version (e.g Ubuntu 16.04):
Centos 7

**Comment by wayneoutthere** [comment]
This affects me quite negatively daily since I operate in this view.  I have attached some screenshots as well here and i'm in 7.10.13
![scrm_due_date_missing](https://user-images.githubusercontent.com/16578346/53524834-5610f200-3a95-11e9-8e7c-efea734a2965.png)

let me know if I can try any hacks to fix it for now ;)

**Comment by edmondklai** [comment]
I have the same problem here.

**Comment by pgorod** [comment]
Can you guys please check if you have these files overridden in `custom` dir?

https://github.com/salesagility/SuiteCRM/pull/5535
https://github.com/salesagility/SuiteCRM/pull/6269

Because those PR's supposedly fix this problem you're getting. I fear that the new code is not taking effect for you, due to other things you had in `custom` created by Studio or by your own PHP code. if so, you should have seen a warning message about it while upgrading.

**Comment by wayneoutthere** [comment]
You might be right.  I inspected  include/ListView/ListViewSubPanel.php and it appears that the line numbers don't match up.  My thought is that probably that is indication I have an old file here instead of new one?  Is it damaging to simply pull these affected files from the most recent SCRM download and swap them out?  I found another problem like this that I fixed this way with the system task assignment notification email.... let me know if there is anything wrong in my thinking or if there is a better/safer way to do this.  Or would that mess everything up?  I'm not very good on this level and especially in Github...  I definitely messed with my custom stuff when I set this up in a hacky way (you saw that thread).  

Or maybe  I could do maybe is 1) back up my whole SCRM 2) backup the database 3) export my customizations (or would this export my problem to the new install?) and then connect them all up again?  do a completely fresh install?  

Thanks for your thoughts here and I think your theory is good....

**Comment by edmondklai** [comment]
I checked and see that in include/ListView/ListViewSubPanel.php has the following lines, which it does.
```
 $list_field['name'] = $list_field['alias'];
                            	// Clone field def from origin field def to alias field def
                            	$alias_field_def = $aItem->field_defs[$field_name];
                            	$alias_field_def['name'] = $list_field['alias'];
                            	// Add alias field def into bean to can render field in subpanel
                            	$aItem->field_defs[$list_field['alias']] = $alias_field_def;
                            	if(!isset($fields[strtoupper($list_field['alias'])]) || empty($fields[strtoupper($list_field['alias'])])) {
                                	global $timedate;
                                	$fields[strtoupper($list_field['alias'])] = (!empty($aItem->$field_name)) ? $aItem->$field_name : $timedate->to_display_date_time($aItem->{$list_field['alias']});
                            	}
```
I checked to see that custom/modules/Tasks/metadata/subpanels/ForHistory.php has these line, which it did.  I removed my custom/modules ForHistory.php and use the modules ForHistory.php and it still not showing the date for Tasks module.

```
		 'date_due'=>array(
			    'vname' => 'LBL_LIST_DUE_DATE',
			    'width' => '10%',
			    'alias' => 'date_due',
			    'sort_by' => 'date_due',
			),
```
I check that my date_due is named date_due, I am not sure where to go from here.

**Comment by algores** [comment]
I have the same problem with SuiteCRM 7.11.3

**Comment by PedroErnst** [comment]
Can confirm, this seems to happen still on the latest hotfix branch, on Opportunities module

**Comment by PedroErnst** [comment]
The above PR should fix this issue.
If anyone could test and confirm this it would be appreciated.

**Comment by wayneoutthere** [comment]
pardon my ignorance but i haven't really done this kind of thing before (testing).  So I guess what I do is copy your code from the fix above and paste into: /ForActivities.php file ?  I'll try this in the next hour hopefully....

**Comment by PedroErnst** [comment]
Hey @wayneoutthere 

Yes in this case the fix is very small and localized, you could apply it manually into your SuiteCRM installation by just copypasting those lines.
Make sure to repair and rebuild :)

**Comment by algores** [comment]
It works with SuiteCRM 7.11.3.
Thank you

**Comment by wayneoutthere** [comment]
thanks guys... i hope to find time to try the fix soon! thanks for the work as always!
