### ISSUE TITLE
7.5: bugs in Activity Streams

### ISSUE THREAD

**Issue by maxxatgit** [salesagility/SuiteCRM#865]
Greetings;
I did a clean install of v7.5 on a CentOS VPS. Whenever I went to Admin >> Activity Streams, the screen would do nothing for about 30 seconds, and then I get an internal server error. I never found anything in the apache logs or in the suitecrm logs. I did some poking around in the code and I found 2 things:

1) In the file modules/SugarFeed/views/view.adminsettings.php, there is a line near the top:

require('modules/SugarFeed/views/view.adminsettings.php');

It seems to be recursively requiring itself. I commented that line out, and now I just get a blank screen when I click Admin >> Activity Streams, but no server error (maybe it needs to require a different file?).

(2) I was getting the following error message in the Activity Stream on my home page:

Warning: Smarty error: unable to read resource: "custom/modules/SugarFeed/Dashlets/SugarFeedDashlet/UserPostForm.tpl" occurred in /home/papatango/public_html/suitecrm/include/Smarty/Smarty.class.php on line 1094

It turns out there is no custom/modules/SugarFeed/Dashlets/SugarFeedDashlet/UserPostForm.tpl, It should be modules/SugarFeed/Dashlets/SugarFeedDashlet/UserPostForm.tpl. I couldn't figure out where that pointer gets created, so I just added a sym link in custom/modules that pointed to  modules/SugarFeed, and those error messages went away.

I hope this helps. I'm testing SuiteCRM, and it seems to be quite the powerhouse CRM.

Regards

**Comment by ExatechIT** [comment]
I am having the same issue, haven't found a solution yet.  This seems to occur when doing a clean install of 7.5, but not when upgrading from 7.4

**Comment by maxxatgit** [comment]
Greetings:
I found the source of this error:

Warning: Smarty error: unable to read resource: "custom/modules/SugarFeed/Dashlets/SugarFeedDashlet/UserPostForm.tpl" occurred in /home/papatango/public_html/suitecrm/include/Smarty/Smarty.class.php on line 1094

In the file: modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php

line 408:
return $ss->fetch('custom/modules/SugarFeed/Dashlets/SugarFeedDashlet/Options.tpl');
should be:
return $ss->fetch('modules/SugarFeed/Dashlets/SugarFeedDashlet/Options.tpl');

line 563:
return $ss->fetch('custom/modules/SugarFeed/Dashlets/SugarFeedDashlet/UserPostForm.tpl');
should be:
return $ss->fetch('modules/SugarFeed/Dashlets/SugarFeedDashlet/UserPostForm.tpl');

That made the error go away on a fresh install.
Hope this helps!

**Comment by ExatechIT** [comment]
Hi,

I made those changes, still getting ERR_EMPTY_RESPONSE when going to Admin
>> Activity Streams

**Comment by maxxatgit** [comment]
Yes, it only addresses the error in the Activity Stream dashlet. Sorry for the mis-communication!

**Comment by ExatechIT** [comment]
Solved this issue, updated the group and owner of the entire directory after install again and it works now.

**Comment by tmcb82** [comment]
Any idea if 7.5.1 resolves this? Or if not when a complete fix will be available? I am testing this to replace another paid CRM but this is making me concerned.

**Comment by ExatechIT** [comment]
7.5.1 does not resolve this.

**Comment by tmcb82** [comment]
It looked like this commit https://github.com/salesagility/SuiteCRM/commit/8ca559fd41e4ab3ba475dc397e6a0415b32f07e5 should have fixed it?

**Comment by maxxatgit** [comment]
I don't think so.

I haven't tested 7.1, but I just looked at  the file modules/SugarFeed/views/view.adminsettings.php.
At line 49, it requires itself:

require('modules/SugarFeed/views/view.adminsettings.php');

Also, in the file: modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php

line 408:
return $ss->fetch('custom/modules/SugarFeed/Dashlets/SugarFeedDashlet/Options.tpl');
should be:
return $ss->fetch('modules/SugarFeed/Dashlets/SugarFeedDashlet/Options.tpl');

**Comment by maxxatgit** [comment]
Greetings;
I see that Softaculous now has version 7.5 of SuiteCRM. I just ran their demo.
#1 The Dashlet error is fixed, it displays correctly
#2 The Activity Streams" link on the Admin page is still broken.
---
Clicking the Activity Streams" link on the Admin page produces a blank page. 

the file "modules/SugarFeed/views/view.adminsettings.php" calls itself recursively.
At line 49, it requires itself: 

require('modules/SugarFeed/views/view.adminsettings.php');

This was not addressed by [8ca995f](https://github.com/salesagility/SuiteCRM/commit/8ca559fd41e4ab3ba475dc397e6a0415b32f07e5)

**Comment by maxxatgit** [comment]
Greetings;
I installed 7.5.1 from softaculous on my vps.
I found 1 more bug:
In the file modules/SugarFeed/views/AdminSettings.php
line 157
$sugar_smarty->display('modules/SugarFeed/AdminSettings.tpl');
should be
$sugar_smarty->display('modules/SugarFeed/tpls/AdminSettings.tpl');
(AdminSettings.tpl has been moved to a sub-directory)

I fixed all of the issues I have found so far:

 - modules/SugarFeed/Dashlets/SugarFeedDashlet/SugarFeedDashlet.php
line 408:
return $ss->fetch('custom/modules/SugarFeed/Dashlets/SugarFeedDashlet/Options.tpl');
changed to:
return $ss->fetch('modules/SugarFeed/Dashlets/SugarFeedDashlet/Options.tpl');

 - modules/SugarFeed/views/view.adminsettings.php" calls itself recursively.
removed line 49:
require('modules/SugarFeed/views/view.adminsettings.php');

 - modules/SugarFeed/views/AdminSettings.php
line 157
$sugar_smarty->display('modules/SugarFeed/AdminSettings.tpl');
changed to:
$sugar_smarty->display('modules/SugarFeed/tpls/AdminSettings.tpl');

And still get a blank screen when I click on the Activity Stream link in the admin page.

I think I've gone about as far as I can with this, I don't know the code *at all* I'm just correcting references to files that have moved. I hope this blank screen issue can be addresses soon.

Thanks!

**Comment by jshwhitlow** [comment]
@maxxatgit in my instance AdminSettings.php is in modules/SugarFeed/ and not within the 'views' sub-directory. Not sure if that is relevant.

I tried a fresh instance and and had no problems. But this problem was still occurring in our instance of 7.5.1 which has been upgraded several times since 7.2.

I believe the upgrade further complicates this problem.

First Error: 
`Fatal error: Maximum execution time of 30 seconds exceeded in /home/aaiglobalcrm/public_html/admin/modules/SugarFeed/views/view.adminsettings.php on line 190`

Step 1:

Made all changes within this thread and then got the following error:

`Fatal error: Class 'ViewAdminsettings' not found in 
/modules/SugarFeed/views/view.adminsettings.php on line 46`

I did a search the class 'ViewAdminsettings' and found another 'view.adminsettings.php' with completely different code in:

/upload/upgrades/patch/SuiteCRM-Upgrade-7.4.x-to-7.5.1-restore/modules/SugarFeed/views/view.adminsettings.php.

The curious thing was that on line 42 it read:
`class ViewAdminsettings extends SugarView `
but on line 46 of the view.adminsettings.php  above on line 46 it read:
`class customViewAdminsettings extends ViewAdminsettings`

I'm not precisely sure what is going on here but there is clearly something wrong with the upgrade process.

My fix for this was to navigate to:
/modules/SugarFeed/views/view.adminsettings.php and change line 46

`class customViewAdminsettings extends ViewAdminsettings`
changed  to   
`class customViewAdminsettings extends SugarView`

This fixed the issue.

I would also like to tie this 'Upgrade-related' issue to this issue as well because I believe it is Upgrade-related as well given that the other issue was related to 7.2, but was appearing in my instance of 7.5.1:
https://github.com/salesagility/SuiteCRM/issues/147
